name: Readme

on:
  issues:
    types: [opened, edited]

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - run: 'echo "$ISSUE_BODY" > temp.txt'
      env: 
        ISSUE_BODY: ${{ github.event.issue.body }}
    - name: create-readme
      if: ${{ startsWith(github.event.issue.title, 'Add handle') }}
      uses: ./action
    - run: rm temp.txt
    - name: Create Pull Request
      if: ${{ startsWith(github.event.issue.title, 'Add handle') }}
      uses: peter-evans/create-pull-request@v2
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        commit-message: ${{ github.event.issue.title }}
        title: ${{ github.event.issue.title }}
        body: |
          Closes #${{ github.event.issue.number }}
        labels: automated pr
        branch: add-new-developer-${{ github.event.issue.number }}
